### ISSUE TITLE
issue when running bash xxxx.sh

### ISSUE THREAD

**Issue by spnadig** [proppy/conda-eda#1]
![image](https://user-images.githubusercontent.com/124022677/216133737-409bcc7a-f1cd-4316-be04-cff773b05b21.png)

**Comment by proppy** [comment]
@spnadig how did you download the installer?

**Comment by proppy** [comment]
make sure you pass the `-L` flag if using curl (otherwise you get an intermediate HTML page)

**Comment by spnadig** [comment]
inovet@furb4:~/tmp$ curl -L -O https://github.com/proppy/conda-eda/releases/download/v0.0-1406-ga734ede/mixed-signal.gf180mcuc-0-Linux-x86_64.sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  772M  100  772M    0     0  14.0M      0  0:00:54  0:00:54 --:--:-- 21.7M
inovet@furb4:~/tmp$ bash [mixed-signal.gf180mcuc-0-Linux-x86_64.sh](http://mixed-signal.gf180mcuc-0-linux-x86_64.sh/) -p silicon-env -b
PREFIX=/usr/local/google/home/inovet/tmp/silicon-env
Unpacking payload ...
                                                                                                                                                                          
Installing base environment...


Downloading and Extracting Packages
                                                                                                                                                                          
                                                                                                                                                                          
PathNotFoundError: /tmp/conda-bld/linux-64/open_pdks.gf180mcuc-1.0.368_0_gb8c6129-20230201_032239.tar.bz2
PathNotFoundError: /tmp/conda-bld/linux-64/ngspice-32.2_1267_g8ee3e3fb4-20230201_032239.tar.bz2

**Comment by proppy** [comment]
Should be:
```
mixed-signal.gf180mcuc-0-Linux-x86_64.sh -p silicon-env -b
```

**Comment by proppy** [comment]
Are you sure the download was complete?

**Comment by spnadig** [comment]
yes

**Comment by proppy** [comment]
Do you get the same issue with earlier release?
https://github.com/proppy/conda-eda/releases

**Comment by spnadig** [comment]
I had used https://github.com/proppy/conda-eda/releases/download/v0.0-1399-g9288596/mixed-signal.gf180mcuc-0-Linux-x86_64.sh and it had worked . But now others are doing the installs from your latest and are having this issue

**Comment by proppy** [comment]
Can you comment with the sha1sum or md5sum of the archive?

**Comment by proppy** [comment]
Managed to reproduce the issue with:
```
~ 🍙 curl -L -o /tmp/test-silicon-env.sh https://github.com/proppy/conda-eda/releases/download/v0.0-1406-ga734ede/mixed-signal.gf180mcuc-0-Linux-x86_64.sh
bash /tmp/test-silicon-env.sh -p /tmp/test-silicon-env -b
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  772M  100  772M    0     0  36.3M      0  0:00:21  0:00:21 --:--:-- 40.2M
~ 🍙 PREFIX=/tmp/test-silicon-envp
Unpacking payload ...
Extracting : blas-1.0-mkl.conda:  86%|████████▌ | 86/100 [00:19<00:00, 15.11it/s]


                                                                                 
Installing base environment...


Downloading and Extracting Packages
open_pdks.gf180mcuc- |                                                    |   0% 
                                                                                 
                                                                                 

PathNotFoundError: /tmp/conda-bld/linux-64/ngspice-32.2_1267_g8ee3e3fb4-20230201_032239.tar.bz2
PathNotFoundError: /tmp/conda-bld/linux-64/open_pdks.gf180mcuc-1.0.368_0_gb8c6129-20230201_032239.tar.bz2
```

**Comment by proppy** [comment]
should be fixed with a7c9e06

**Comment by proppy** [comment]
New installer with the fixes are ready: 
https://github.com/proppy/conda-eda/releases/tag/v0.0-1409-ga7c9e06

**Comment by proppy** [comment]
actuall I think this is a regression in constructor (the installer generator) in https://github.com/conda/constructor/pull/605 and https://github.com/conda/constructor/pull/503.

attempting to revert to an older version in b5131ac671c0f3a7e5519010bb422e7eee63f357

**Comment by proppy** [comment]
Should be fixed with the new installer:
https://github.com/proppy/conda-eda/releases/tag/v0.0-1424-g1e0ce17
```
curl -L -o /tmp/silicon-installer.sh https://github.com/proppy/conda-eda/releases/download/v0.0-1424-g1e0ce17/mixed-signal.gf180mcuc-0-Linux-x86_64.sh
bash /tmp/silicon-installer.sh -p silicon-env -b
```

This was not actually a conda regression but us incorrectly making the open_pdks.gf180mcuc package as public: https://github.com/proppy/conda-eda/commit/0425fa72485b2b2e59d35313926d334c7a78420b
