### ISSUE TITLE
Netlist issue from Magic

### ISSUE THREAD

**Issue by spnadig** [proppy/conda-eda#3]
In Magic when we do a extract all -> ext2spice to get post layout extraction netlist - does not match definitions for xschem netlist while running ngspice sim on the extracted subcircuit
**Error while running post-extraction simulation on ngspice**
<img width="742" alt="image" src="https://user-images.githubusercontent.com/124022677/216737799-6236fe62-2bc0-4b6c-b98e-10be3bd5ad6b.png">

**Comment by spnadig** [comment]
Found that the issue is magic writes the netlist with transistor names: nmos_3p3 and pmos_3pm. Whereas, xschem/ngpice expects the netlist to have nfet_03v3 and pfet_03v3. Magic ext2spice script needs to be modified to accommodate this

**Comment by spnadig** [comment]
But the order of terminals for netlist from magic may also be an issue. Also, pfets get additional terminal in magic extracted netlist...

**Comment by proppy** [comment]
Seems like we should report this against https://github.com/RTimothyEdwards/open_pdks, to change the magic enablement for the PDK in https://github.com/RTimothyEdwards/open_pdks/tree/master/gf180mcu/magic to match the klayout pcells convention.

**Comment by proppy** [comment]
> Found that the issue is magic writes the netlist with transistor names: nmos_3p3 and pmos_3pm. Whereas, xschem/ngpice expects the netlist to have nfet_03v3 and pfet_03v3. Magic ext2spice script needs to be modified to accommodate this

Seems like it's already has been fixed in https://github.com/RTimothyEdwards/open_pdks/commit/9c9ffda7aa1da807db9a8c6128678e6f96b6adc7, we just need to make sure we use the latest version of the open_pdks.

**Comment by proppy** [comment]
Fixed with https://github.com/proppy/conda-eda/commit/528579705352e6010c15ee9f135c169341505bdd

New version of the installer available here https://github.com/proppy/conda-eda/releases/tag/v0.0-1435-g5285797
